version: "3.8"
services:

  php-apache-server:
    build:
      context: .
      target: php_apache
    image: php-apache
    container_name: php-apache
    volumes:
      - ./app:/var/www/html
      - ./logs/php-apache:/var/log/apache2
    privileged: true
    env_file:
      - php.env
    ports: 
      - 8000:80
  
  mysql:
    build:
      context: .
      target: mysql
    image: mysql
    env_file:
      - mysql.env
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    restart: on-failure

  adminer:
    build:
      context: .
      target: adminer
    image: adminer
    container_name: adminer
    env_file:
      - adminer.env
    ports:
      - 3000:8080
    restart: on-failure